# 00. PyTorch Fundamentals
* source: https://www.learnpytorch.io/01_pytorch_workflow/
* https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb
---------------------
* conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

In [1]:
!nvidia-smi

Wed Feb 15 20:05:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8     3W /  50W |    267MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.device('cuda')

device(type='cuda')

In [4]:
print(torch.__version__)
print(pd.__version__)
print(np.__version__)

1.13.1+cu116
1.4.4
1.21.5


## Intro to Tensors

### Scalar
* https://pytorch.org/docs/stable/tensors.html

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# number of dimensions
scalar.ndim

0

In [7]:
# return tensor as python int
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
# does not work
# vector.item()

## MATRIX

In [11]:
MATRIX = torch.tensor([[7,8], [9,10]])
print(MATRIX)
print(MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX[1][0]

tensor(9)

In [15]:
MATRIX.shape

torch.Size([2, 2])

## TENSOR

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [17]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0][0]

tensor([1, 2, 3])

In [20]:
TENSOR[0][0][1]

tensor(2)

### Random Tensors
* https://pytorch.org/docs/stable/generated/torch.rand.html

In [21]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6182, 0.8872, 0.7702, 0.7978],
        [0.7189, 0.5941, 0.5617, 0.0267],
        [0.8537, 0.9587, 0.6739, 0.2578]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2340, 0.7732, 0.4967, 0.5120],
         [0.3584, 0.2126, 0.8012, 0.9420],
         [0.9437, 0.7967, 0.6848, 0.4368]]])

In [24]:
# image size tensor
image_tensor = torch.rand(size=(224,224,3))
image_tensor

tensor([[[0.9105, 0.1683, 0.2645],
         [0.4785, 0.9445, 0.2200],
         [0.7185, 0.7744, 0.5233],
         ...,
         [0.4621, 0.2816, 0.7475],
         [0.8951, 0.2086, 0.5100],
         [0.2874, 0.6450, 0.6045]],

        [[0.2538, 0.3635, 0.2085],
         [0.9030, 0.5842, 0.7046],
         [0.9455, 0.2004, 0.5582],
         ...,
         [0.8734, 0.3731, 0.6964],
         [0.2140, 0.4188, 0.5877],
         [0.7137, 0.5043, 0.4168]],

        [[0.7195, 0.1165, 0.0389],
         [0.9439, 0.0417, 0.5296],
         [0.1060, 0.7038, 0.9436],
         ...,
         [0.7648, 0.7277, 0.4575],
         [0.5493, 0.4823, 0.5859],
         [0.2704, 0.2793, 0.2651]],

        ...,

        [[0.7113, 0.8396, 0.0244],
         [0.1856, 0.3671, 0.8591],
         [0.8021, 0.7423, 0.6465],
         ...,
         [0.3372, 0.5534, 0.8889],
         [0.9590, 0.6030, 0.3862],
         [0.2613, 0.8865, 0.8919]],

        [[0.4834, 0.9139, 0.7412],
         [0.9034, 0.9856, 0.6857],
         [0.

In [25]:
image_tensor.shape

torch.Size([224, 224, 3])

In [26]:
image_tensor.ndim

3

In [27]:
# image size tensor
tensor2 = torch.rand(size=(224,224,3,3))
tensor2

tensor([[[[0.2704, 0.6826, 0.2071],
          [0.1574, 0.2049, 0.0274],
          [0.9386, 0.1841, 0.3566]],

         [[0.1593, 0.8490, 0.9931],
          [0.9845, 0.4406, 0.3689],
          [0.1015, 0.8104, 0.9359]],

         [[0.2356, 0.1589, 0.6226],
          [0.4803, 0.1699, 0.4183],
          [0.9307, 0.3266, 0.9710]],

         ...,

         [[0.5529, 0.5746, 0.2793],
          [0.6713, 0.4655, 0.0431],
          [0.8779, 0.3176, 0.8308]],

         [[0.3213, 0.6155, 0.6887],
          [0.8046, 0.2034, 0.3486],
          [0.5685, 0.4183, 0.6845]],

         [[0.4463, 0.6754, 0.5162],
          [0.5335, 0.6383, 0.0427],
          [0.9898, 0.8591, 0.2151]]],


        [[[0.6830, 0.8691, 0.6105],
          [0.5219, 0.0473, 0.0016],
          [0.5257, 0.3192, 0.5401]],

         [[0.5354, 0.2774, 0.2265],
          [0.2563, 0.0084, 0.9183],
          [0.7553, 0.6683, 0.8073]],

         [[0.9520, 0.1315, 0.9783],
          [0.3761, 0.7420, 0.9111],
          [0.3710, 0.5106, 0.78

In [28]:
tensor2.ndim

4

In [29]:
tensor2.shape

torch.Size([224, 224, 3, 3])

### Zeros and Ones

In [30]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Range of Tensor
* https://pytorch.org/docs/stable/generated/torch.arange.html?highlight=arange#torch.arange

In [33]:
# torch.arange

range = torch.arange(0, 10, 3)
range

tensor([0, 3, 6, 9])

### Tensor dtypes

In [34]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype=None)
float_32_tensor.dtype

torch.float32

In [35]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

** Tensor dtypes is one of the 3 big issues with pytorch and deep learning

1. Tensor not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [36]:
float_32_tensor = torch.tensor([3.,6.,9.],  # shape
                            dtype=None, # data type
                            device=None,  # ('cpu' or 'cuda')
                            requires_grad=False # whether or not to track gradients
                            )
float_32_tensor.dtype

torch.float32

In [37]:
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [38]:
a = float_16 * float_32_tensor
a

tensor([ 9., 36., 81.])

In [39]:
a.dtype

torch.float32

### Getting informations from tensors

In [40]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3533, 0.3321, 0.8536, 0.9993],
        [0.5371, 0.3096, 0.1094, 0.2211],
        [0.3859, 0.6240, 0.1457, 0.1524]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [41]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor ** 2

tensor([1, 4, 9])

### Built in functions

In [44]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [45]:
torch.add(tensor, tensor)

tensor([2, 4, 6])

In [46]:
torch.div(tensor, tensor)

tensor([1., 1., 1.])

In [47]:
tensor @ tensor

tensor(14)

In [48]:
tensor * tensor

tensor([1, 4, 9])

#### Multiplication
1. Element wise
2. Dot product

In [49]:
# element wise
tensor * tensor

tensor([1, 4, 9])

In [50]:
# dot product 
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# # Shapes need to be in the right way  
# tensor_A = torch.tensor([[1, 2],
#                          [3, 4],
#                          [5, 6]], dtype=torch.float32)

# tensor_B = torch.tensor([[7, 10],
#                          [8, 11], 
#                          [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [52]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B)

tensor([[ 23.,  32.],
        [ 53.,  74.],
        [ 83., 116.]])

In [53]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [12,13]], dtype=torch.float32)

tensor_A * tensor_B

tensor([[ 7., 20.],
        [24., 44.],
        [60., 78.]])

#### Transpose

In [54]:
tensor_B

tensor([[ 7., 10.],
        [ 8., 11.],
        [12., 13.]])

In [55]:
tensor_B.T

tensor([[ 7.,  8., 12.],
        [10., 11., 13.]])

In [56]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # transposed

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Tensor Aggregation

In [57]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
torch.min(x)

tensor(0)

In [59]:
x.min()

tensor(0)

In [60]:
torch.max(x)

tensor(90)

In [62]:
# x.mean()
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [65]:
x = x.type(torch.float32)

In [66]:
x.mean()

tensor(45.)

In [67]:
x.sum()

tensor(450.)

### Finding positional min and max

In [68]:
x.argmax()

tensor(9)

In [74]:
x.argwhere()

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [70]:
x.argsort()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor(0)

In [75]:
x[5]

tensor(50.)

In [77]:
x[x.argmax()]

tensor(90.)

### Reshapeing, view, stacking, squeezing, unsqueezing and permute tensors

* reshape: changes the shape
* view: return a view of an input tensor, but keeps in memory the original tensor
* stacking: vstack and hstack, concatenate  multiple tensors on top of each other
* squeeze: removes all 1 dim from a tensor
* unsqueeze: add a 1 dim to a tensor
* permute: return a view of the input with dims permuted (swapped) in a certain way

In [78]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
x.shape

torch.Size([9])

In [82]:
# reshape 
# x_reshaped = x.reshape(1,7)
# x_reshaped RuntimeError: shape '[1, 7]' is invalid for input of size 9

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [84]:
# reshape 
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [85]:
x = torch.arange(0., 10.)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
x_reshaped = x.reshape(5, 2)
x_reshaped

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [87]:
x.shape

torch.Size([10])

In [89]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [91]:
z.shape

torch.Size([1, 9])

In [94]:
# stacking tensors
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [95]:
# hstack
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [97]:
# vstack
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [115]:
# squeeze
a = torch.arange(1,10,1)
# a = torch.rand(size=(3,2))
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
torch.unsqueeze(a, dim=-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [122]:
torch.squeeze(a, dim=0)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
torch.squeeze(a, dim=0)

tensor([[0.0145, 0.0885],
        [0.9338, 0.3944],
        [0.8386, 0.0041]])

In [123]:
torch.unsqueeze(a, dim=-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [124]:
torch.unsqueeze(a, dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [125]:
torch.unsqueeze(a, dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [126]:
torch.unsqueeze(a, dim=-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [127]:
torch.unsqueeze(a, dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [136]:
# permute: orders the dims
b = torch.rand(size=(224,224,3))
b

tensor([[[0.8461, 0.4736, 0.0606],
         [0.8842, 0.7243, 0.5355],
         [0.6030, 0.3656, 0.3288],
         ...,
         [0.1254, 0.4596, 0.7326],
         [0.0022, 0.5402, 0.9669],
         [0.8891, 0.3545, 0.9448]],

        [[0.7784, 0.8143, 0.1950],
         [0.8309, 0.3985, 0.7283],
         [0.0717, 0.4706, 0.9092],
         ...,
         [0.2401, 0.0371, 0.3881],
         [0.5212, 0.2649, 0.0881],
         [0.4979, 0.6755, 0.0037]],

        [[0.5748, 0.1625, 0.1853],
         [0.3738, 0.2092, 0.0900],
         [0.2114, 0.5079, 0.2459],
         ...,
         [0.0302, 0.7357, 0.6101],
         [0.4007, 0.7652, 0.2675],
         [0.5066, 0.0015, 0.9884]],

        ...,

        [[0.1428, 0.1553, 0.1187],
         [0.0913, 0.9338, 0.3302],
         [0.8968, 0.6427, 0.2970],
         ...,
         [0.9780, 0.8646, 0.3231],
         [0.3585, 0.2509, 0.5719],
         [0.0618, 0.1725, 0.3270]],

        [[0.7151, 0.6889, 0.0043],
         [0.9647, 0.1836, 0.4033],
         [0.

In [139]:
c = b.permute(2, 0, 1)
c

tensor([[[0.8461, 0.8842, 0.6030,  ..., 0.1254, 0.0022, 0.8891],
         [0.7784, 0.8309, 0.0717,  ..., 0.2401, 0.5212, 0.4979],
         [0.5748, 0.3738, 0.2114,  ..., 0.0302, 0.4007, 0.5066],
         ...,
         [0.1428, 0.0913, 0.8968,  ..., 0.9780, 0.3585, 0.0618],
         [0.7151, 0.9647, 0.1524,  ..., 0.8184, 0.6745, 0.1236],
         [0.4045, 0.4237, 0.3117,  ..., 0.2172, 0.8912, 0.4411]],

        [[0.4736, 0.7243, 0.3656,  ..., 0.4596, 0.5402, 0.3545],
         [0.8143, 0.3985, 0.4706,  ..., 0.0371, 0.2649, 0.6755],
         [0.1625, 0.2092, 0.5079,  ..., 0.7357, 0.7652, 0.0015],
         ...,
         [0.1553, 0.9338, 0.6427,  ..., 0.8646, 0.2509, 0.1725],
         [0.6889, 0.1836, 0.2169,  ..., 0.2357, 0.0292, 0.8901],
         [0.2666, 0.4415, 0.3539,  ..., 0.1934, 0.1355, 0.4322]],

        [[0.0606, 0.5355, 0.3288,  ..., 0.7326, 0.9669, 0.9448],
         [0.1950, 0.7283, 0.9092,  ..., 0.3881, 0.0881, 0.0037],
         [0.1853, 0.0900, 0.2459,  ..., 0.6101, 0.2675, 0.

In [138]:
b.shape

torch.Size([224, 224, 3])

In [140]:
c.shape

torch.Size([3, 224, 224])

## Indexing

In [141]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
x = x.reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [146]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [148]:
x[0][1][2]

tensor(6)

In [149]:
x[0][1][2].item()

6

In [150]:
type(x[0][1][2].item())

int

In [151]:
type(x[0][1][2])

torch.Tensor

In [152]:
x[0][2][2]

tensor(9)

In [153]:
x[:,0]

tensor([[1, 2, 3]])

In [161]:
x[:, 0:2, 1:1]

tensor([], size=(1, 2, 0), dtype=torch.int64)

In [171]:
x[:, 1:2, :2]

tensor([[[4, 5]]])

In [181]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [183]:
x[:,:,2]

tensor([[3, 6, 9]])

## Numpy and Tensors
* from array to tensor = torch.from_numpy(array_np)
* from tensor to array = torch.Tensor.numpy(tensor)


In [184]:
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [189]:
tensor = torch.from_numpy(array)
tensor, type(tensor)

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.Tensor)

In [190]:
back_to_array = torch.Tensor.numpy(tensor)
back_to_array, type(back_to_array)

(array([1., 2., 3., 4., 5., 6., 7.]), numpy.ndarray)

## Reproducibility (trying to take random out of random)

In [191]:
torch.rand(3,3)

tensor([[0.7964, 0.9654, 0.5818],
        [0.7218, 0.5418, 0.7099],
        [0.5775, 0.2307, 0.0373]])

In [192]:
torch.rand(3,3)

tensor([[0.4000, 0.0674, 0.4727],
        [0.5374, 0.9474, 0.7507],
        [0.5055, 0.9338, 0.4861]])

In [198]:
torch.manual_seed(1)
torch.rand(3,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])

In [199]:
torch.manual_seed(1)
torch.rand(3,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])

## CPU and GPU

In [203]:
!nvidia-smi

Wed Feb 15 21:33:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8     4W /  50W |    317MiB /  4096MiB |     16%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [204]:
torch.cuda.is_available()

True

In [205]:
torch.device('cuda')

device(type='cuda')

In [207]:
torch.cuda.device_count()

1

In [206]:
torch.cuda.current_device()

0

In [208]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1650'

In [209]:
tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [210]:
tensor = torch.tensor([1,2,3], device='cuda')

tensor, tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [211]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [212]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [214]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3], dtype=int64)